<?php

namespace Database\Seeders;

use App\Models\AmWorkOrderLifecycleModel;
use App\Models\AmWorkOrderLifecycleState;
use App\Models\Tenant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AmWorkOrderLifecycleStateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lifecycleStates = [
            [
                'lifecycle_state' => 'Completed',
                'name' => 'Work is complete',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'InProcess',
                'request_lifecycle_state_id' => 'Finished',
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => false,
                'work_order_allow_line_delete' => false,
                'work_order_allow_scheduling' => false,
                'work_order_create_job' => false,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'Finished',
                'name' => 'Work order is financially closed',
                'close_activities' => true,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'Completed',
                'request_lifecycle_state_id' => null,
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => false,
                'work_order_allow_delete' => false,
                'work_order_allow_line_delete' => false,
                'work_order_allow_scheduling' => false,
                'work_order_create_job' => false,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'InProgress',
                'name' => 'Work has started',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'InProcess',
                'request_lifecycle_state_id' => null,
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => false,
                'work_order_allow_line_delete' => false,
                'work_order_allow_scheduling' => false,
                'work_order_create_job' => false,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => true,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'New',
                'name' => 'New work order',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'Created',
                'request_lifecycle_state_id' => 'InProgress',
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => true,
                'work_order_allow_line_delete' => true,
                'work_order_allow_scheduling' => true,
                'work_order_create_job' => true,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'Pending',
                'name' => 'Work order is pending, waiting on part or contractor',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'Estimated',
                'request_lifecycle_state_id' => null,
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => true,
                'work_order_allow_line_delete' => false,
                'work_order_allow_scheduling' => true,
                'work_order_create_job' => false,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'Released',
                'name' => 'Work order has been released',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'InProcess',
                'request_lifecycle_state_id' => null,
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => true,
                'work_order_allow_line_delete' => true,
                'work_order_allow_scheduling' => true,
                'work_order_create_job' => true,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
            [
                'lifecycle_state' => 'Scheduled',
                'name' => 'Work order has been scheduled',
                'close_activities' => false,
                'copy_forecast_expense' => false,
                'copy_forecast_hour' => false,
                'copy_forecast_item' => false,
                'maintenance_asset_lifecycle_state_id' => null,
                'maintenance_plan_counter_reset' => false,
                'post_work_order_journals' => false,
                'project_status' => 'InProcess',
                'request_lifecycle_state_id' => null,
                'schedule_end' => false,
                'schedule_ready' => false,
                'schedule_start' => false,
                'update_maintenance_asset_bom' => false,
                'validate_committed_cost' => false,
                'validate_committed_cost_info_type' => 'Information',
                'validate_fault_cause' => false,
                'validate_fault_cause_info_type' => 'Information',
                'validate_fault_remedy' => false,
                'validate_fault_remedy_info_type' => 'Information',
                'validate_fault_symptom' => false,
                'validate_fault_symptom_info_type' => 'Information',
                'validate_production_stop' => false,
                'validate_production_stop_info_type' => 'Information',
                'work_order_active' => true,
                'work_order_allow_delete' => false,
                'work_order_allow_line_delete' => false,
                'work_order_allow_scheduling' => false,
                'work_order_create_job' => false,
                'work_order_line_schedule_delete' => false,
                'work_order_pool_delete' => false,
                'work_order_set_actual_end' => false,
                'work_order_set_actual_end_default' => 'ScheduledEndExpectedEnd',
                'work_order_set_actual_start' => false,
                'work_order_set_actual_start_default' => 'ScheduledStartExpectedStart',
                'work_order_validate_checklist' => false,
                'work_order_validate_checklist_info_type' => 'Information',
            ],
        ];

        $tenants = Tenant::all();

        foreach ($tenants as $tenant) {
            // Get the lifecycle model for this tenant
            $lifecycleModel = AmWorkOrderLifecycleModel::where('tenant_id', $tenant->id)
                ->where('lifecycle_model_name', 'Standard')
                ->first();

            if (!$lifecycleModel) {
                continue;
            }

            foreach ($lifecycleStates as $lifecycleState) {
                $existingState = AmWorkOrderLifecycleState::where('tenant_id', $tenant->id)
                    ->where('lifecycle_state', $lifecycleState['lifecycle_state'])
                    ->first();

                if (!$existingState) {
                    AmWorkOrderLifecycleState::create([
                        'lifecycle_state' => $lifecycleState['lifecycle_state'],
                        'name' => $lifecycleState['name'],
                        'close_activities' => $lifecycleState['close_activities'],
                        'copy_forecast_expense' => $lifecycleState['copy_forecast_expense'],
                        'copy_forecast_hour' => $lifecycleState['copy_forecast_hour'],
                        'copy_forecast_item' => $lifecycleState['copy_forecast_item'],
                        'maintenance_asset_lifecycle_state_id' => $lifecycleState['maintenance_asset_lifecycle_state_id'],
                        'maintenance_plan_counter_reset' => $lifecycleState['maintenance_plan_counter_reset'],
                        'post_work_order_journals' => $lifecycleState['post_work_order_journals'],
                        'project_status' => $lifecycleState['project_status'],
                        'request_lifecycle_state_id' => $lifecycleState['request_lifecycle_state_id'],
                        'schedule_end' => $lifecycleState['schedule_end'],
                        'schedule_ready' => $lifecycleState['schedule_ready'],
                        'schedule_start' => $lifecycleState['schedule_start'],
                        'update_maintenance_asset_bom' => $lifecycleState['update_maintenance_asset_bom'],
                        'validate_committed_cost' => $lifecycleState['validate_committed_cost'],
                        'validate_committed_cost_info_type' => $lifecycleState['validate_committed_cost_info_type'],
                        'validate_fault_cause' => $lifecycleState['validate_fault_cause'],
                        'validate_fault_cause_info_type' => $lifecycleState['validate_fault_cause_info_type'],
                        'validate_fault_remedy' => $lifecycleState['validate_fault_remedy'],
                        'validate_fault_remedy_info_type' => $lifecycleState['validate_fault_remedy_info_type'],
                        'validate_fault_symptom' => $lifecycleState['validate_fault_symptom'],
                        'validate_fault_symptom_info_type' => $lifecycleState['validate_fault_symptom_info_type'],
                        'validate_production_stop' => $lifecycleState['validate_production_stop'],
                        'validate_production_stop_info_type' => $lifecycleState['validate_production_stop_info_type'],
                        'work_order_active' => $lifecycleState['work_order_active'],
                        'work_order_allow_delete' => $lifecycleState['work_order_allow_delete'],
                        'work_order_allow_line_delete' => $lifecycleState['work_order_allow_line_delete'],
                        'work_order_allow_scheduling' => $lifecycleState['work_order_allow_scheduling'],
                        'work_order_create_job' => $lifecycleState['work_order_create_job'],
                        'work_order_line_schedule_delete' => $lifecycleState['work_order_line_schedule_delete'],
                        'work_order_pool_delete' => $lifecycleState['work_order_pool_delete'],
                        'work_order_set_actual_end' => $lifecycleState['work_order_set_actual_end'],
                        'work_order_set_actual_end_default' => $lifecycleState['work_order_set_actual_end_default'],
                        'work_order_set_actual_start' => $lifecycleState['work_order_set_actual_start'],
                        'work_order_set_actual_start_default' => $lifecycleState['work_order_set_actual_start_default'],
                        'work_order_validate_checklist' => $lifecycleState['work_order_validate_checklist'],
                        'work_order_validate_checklist_info_type' => $lifecycleState['work_order_validate_checklist_info_type'],
                        'lifecycle_model_id' => $lifecycleModel->id,
                        'tenant_id' => $tenant->id,
                    ]);
                }
            }
        }
    }
} 